# Generated by Django 5.0.1 on 2024-03-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_inventory_quantity_inventory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='position',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
