""" apps.py
generated by Sebastion Root
"""
from django.apps import AppConfig

class VillageConfig(AppConfig):
    # Define the default auto-generated primary key field type for models in this app
    default_auto_field = 'django.db.models.BigAutoField'
    # Specify the name of the app
    name = 'village'

